AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  A function that handles a Slack slash command, creates a new issue and
  sends details to the user.

Parameters:
  GitHubToken:
    Description: A token for calling GitHub API.
    Type: String

Resources:
  issueCreator:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: src/index.handler
      Runtime: nodejs8.10
      CodeUri: .
      Description: >-
        A function that handles a Slack slash command, creates a new issue and
        sends details to the user.
      MemorySize: 128
      Timeout: 5
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /issue/new
            Method: POST
      Environment:
        Variables:
          GITHUB_TOKEN: !Ref GitHubToken

Outputs:
  RequestURL:
    Description: "API Gateway endpoint URL to add the Slack slash command configuration."
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/issue/new"